# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod" 
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      gomod-all:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "devcontainers" 
    directory: "/" 
    schedule:
      interval: "monthly"
    groups:
      devcontainers-all:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip" 
    directory: "/" 
    schedule:
      interval: "monthly"
    groups:
      pip-all:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions-all:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
