# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
      - documentation
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Bug Fixes 🐞
      labels:
        - bugfix
    - title: Other Changes
      labels:
        - "*"
