server:
  host: "localhost"
  port: 8080
  rpcPort: 8081

cloudPlugins:
  - name: "azure"
    host: "localhost"
    port: 8082

tagService:
  host: "localhost"
  port: 8083



namespaces: 
  default:
    - name: "azure"
      deployment: "/subscriptions/2051cdb8-80a4-48a4-840c-ac989eb486a2/resourceGroups/juilant-rg"
