server: 
  host: "localhost"
  port: 8080
  rpcPort: 8081

cloudPlugins:
  - name: "gcp"
    host: "localhost"
    port: 10001
  - name: "azure"
    host: "localhost"
    port: 10002

namespaces: 
  default:
    - name: "azure"
      deployment: "/subscriptions/<sub-id>/resourceGroups/<rg-name>"
    - name: "gcp"
      deployment: "projects/<project-name>"

tagService:
  host: "localhost"
  port: 6000
