linters:
  enable:
  - goheader
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goheader
linters-settings:
  # Settings for linter 'goheader'
  #
  # This is used to validate that all go files have the required copyright header.
  goheader:
    template-path: build/header.tmpl
run:
  build-tags:
    - unit
    - integration
