server: 
  host: "localhost"
  port: 8080
  rpcPort: 8081

cloudPlugins:
  - name: "gcp"
    host: "localhost"
    port: 1026
    invDeployment: "projects/invisinets"
  - name: "azure"
    host: "localhost"
    port: 1027
    invDeployment: "/subscriptions/<subid>/resourceGroups/invisinets-demo"

tagService:
  host: "localhost"
  port: 6000
