server: 
  host: "localhost"
  port: 8080
  rpcPort: 8081

cloudPlugins:
  - name: "azure"
    host: "localhost"
    port: 1001

namespaces: 
  default:
    cloudDeployments:
      - name: "azure"
        deployment: "/subscriptions/4ba880a9-fe39-4105-98e1-909297ff5bb8/resourceGroups/invisinets-demo"

tagService:
  host: "localhost"
  port: 6000
