name: Functional Tests Approval

on:
  push:
    branches:
      - main
      - release/*
    tags:
      - v*
    paths-ignore:
      - '.devcontainer/**'
      - '.githooks/**'
      - 'docs/**'
      - '**.md'
      - '**.rst'
  pull_request:
    branches:
      - main
      - features/*
      - release/*
    paths-ignore:
      - '.devcontainer/**'
      - '.githooks/**'
      - 'docs/**'
      - '**.md'
      - '**.rst'

jobs:
  functional-tests-approval:
    name: Functional Tests Approval
    runs-on: ubuntu-latest
    environment: functional-tests
    steps:
      - name: Save commit SHA
        run: |
          mkdir -p ./commit_sha
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo ${{ github.event.pull_request.head.sha }} > ./commit_sha/commit_sha
          elif [ "${{ github.event_name }}" == "push" ]; then
            echo $GITHUB_SHA > ./commit_sha/commit_sha
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: commit_sha
          path: commit_sha/
