name: Functional Tests Approval

on:
  push:
    branches:
      - main
      - release/*
    tags:
      - v*
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - main
      - features/*
      - release/*
    paths-ignore:
      - 'docs/**'

jobs:
  functional-tests-approval:
    name: Functional Tests Approval
    runs-on: ubuntu-latest
    environment: functional-tests
    steps:
      - name: Save commit SHA
        run: |
          mkdir -p ./github_sha
          echo "GITHUB_SHA = $GITHUB_SHA"
          echo $GITHUB_SHA > ./github_sha/github_sha
      - uses: actions/upload-artifact@v4
        with:
          name: github_sha
          path: github_sha/
