name: "Sphinx: Render docs"

on:
  push:
    branches:
      - main
      - release/*
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Build docs
        working-directory: ./docs
        run: |
          pip install -r requirements.txt
          make html
      - name: Upload doc artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/build/html/
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
